import os

L = []
a = L.append

a("")
a("    // =========================================================================")
a("    // CPU Initialization")
a("    // =========================================================================")
a("")
a("    proc K::cpu_init() -> UInt32 {")
a('        emit "XDV CPU: Initializing CPU subsystem";')
a("        let gdt_status = setup_gdt();")
a("        if gdt_status == STATUS_OK {")
a("            let idt_status = setup_idt();")
a("            if idt_status == STATUS_OK {")
a("                let tss_status = setup_tss();")
a("                if tss_status == STATUS_OK {")
a("                    let cr4_status = configure_cr4();")
a("                    if cr4_status == STATUS_OK {")
a("                        let efer_status = configure_efer();")
a("                        if efer_status == STATUS_OK {")
a('                            emit "XDV CPU: CPU subsystem initialized";')
a("                            return STATUS_OK;")
a("                        }")
a('                        emit "XDV CPU: EFER configuration failed";')
a("                        return STATUS_INIT_ERROR;")
a("                    }")
a('                    emit "XDV CPU: CR4 configuration failed";')
a("                    return STATUS_INIT_ERROR;")
a("                }")
a('                emit "XDV CPU: TSS setup failed";')
a("                return STATUS_INIT_ERROR;")
a("            }")
a('            emit "XDV CPU: IDT setup failed";')
a("            return STATUS_INIT_ERROR;")
a("        }")
a('        emit "XDV CPU: GDT setup failed";')
a("        return STATUS_INIT_ERROR;")
a("    }")
a("")
a("    // =========================================================================")
a("    // GDT (Global Descriptor Table)")
a("    // =========================================================================")
a("")
a("    proc K::setup_gdt() -> UInt32 {")
a('        emit "XDV CPU: Setting up GDT";')
a("")
a("        // Entry 0: NULL descriptor (all zeros)")
a("        let e0 = encode_gdt_entry(0, 0, 0, 0, 0, 0, 0);")
a("        if e0 != 1 {")
a("            return STATUS_INIT_ERROR;")
a("        }")
a("")
a("        // Entry 1: Kernel code segment (selector 0x0008)")
a("        let e1 = encode_gdt_entry(65535, 0, 0, 0x9B, 0xA0, 15, 0);")
a("        if e1 != 1 {")
a("            return STATUS_INIT_ERROR;")
a("        }")
a("")
a("        // Entry 2: Kernel data segment (selector 0x0010)")
a("        let e2 = encode_gdt_entry(65535, 0, 0, 0x93, 0xC0, 15, 0);")
a("        if e2 != 1 {")
a("            return STATUS_INIT_ERROR;")
a("        }")
a("")
a("        // Entry 3: User code segment (selector 0x001B)")
a("        let e3 = encode_gdt_entry(65535, 0, 0, 0xFB, 0xA0, 15, 0);")
a("        if e3 != 1 {")
a("            return STATUS_INIT_ERROR;")
a("        }")
a("")
a("        // Entry 4: User data segment (selector 0x0023)")
a("        let e4 = encode_gdt_entry(65535, 0, 0, 0xF3, 0xC0, 15, 0);")
a("        if e4 != 1 {")
a("            return STATUS_INIT_ERROR;")
a("        }")
a("")
a("        // Entry 5: TSS descriptor (selector 0x0028)")
a("        let e5 = encode_gdt_entry(103, 0, 0, 0x89, 0x00, 0, 0);")
a("        if e5 != 1 {")
a("            return STATUS_INIT_ERROR;")
a("        }")
a("")
a("        // Validate selectors against entry indices")
a("        let s1 = validate_selector(GDT_KERNEL_CODE_SELECTOR, 1);")
a("        if s1 != STATUS_OK {")
a("            return STATUS_INIT_ERROR;")
a("        }")
a("        let s2 = validate_selector(GDT_KERNEL_DATA_SELECTOR, 2);")
a("        if s2 != STATUS_OK {")
a("            return STATUS_INIT_ERROR;")
a("        }")
a("        let s3 = validate_selector(GDT_USER_CODE_SELECTOR, 3);")
a("        if s3 != STATUS_OK {")
a("            return STATUS_INIT_ERROR;")
a("        }")
a("        let s4 = validate_selector(GDT_USER_DATA_SELECTOR, 4);")
a("        if s4 != STATUS_OK {")
a("            return STATUS_INIT_ERROR;")
a("        }")
a("        let s5 = validate_selector(GDT_TSS_SELECTOR, 5);")
a("        if s5 != STATUS_OK {")
a("            return STATUS_INIT_ERROR;")
a("        }")
a("")
a("        // Build GDT pointer: 16-bit limit + 64-bit base address")
a("        let ptr_status = encode_gdt_ptr(GDT_LIMIT, GDT_BASE_ADDRESS);")
a("        if ptr_status != STATUS_OK {")
a("            return STATUS_INIT_ERROR;")
a("        }")
a("")
a('        emit "XDV CPU: GDT configured with 6 entries";')
a("        return STATUS_OK;")
a("    }")
a("")
a("    // Encode a GDT entry from component fields (limit, access, granularity)")
a("    // Returns 1 on success (simulated; actual hardware writes memory)")
a("    proc K::encode_gdt_entry(")
a("        limit_0_15: UInt16,")
a("        base_0_15: UInt16,")
a("        base_16_23: UInt8,")
a("        access: UInt8,")
a("        granularity: UInt8,")
a("        limit_16_19: UInt8,")
a("        base_24_31: UInt8")
a("    ) -> UInt64 {")
a("        if access == 0 {")
a("            if base_0_15 == 0 {")
a("                if limit_0_15 == 0 {")
a("                    return 1;")
a("                }")
a("            }")
a("            if access == 0 {")
a("                return 0;")
a("            }")
a("        }")
a("        if limit_0_15 > 65535 {")
a("            return 0;")
a("        }")
a("        if base_0_15 > 65535 {")
a("            return 0;")
a("        }")
a("        let low_32 = build_gdt_entry_low(limit_0_15, base_0_15);")
a("        let high_8 = build_gdt_entry_high(base_24_31, limit_16_19, granularity, access, base_16_23);")
a("        return 1;")
a("    }")
a("")
a("    // Build lower 32 bits of GDT entry: limit[0:15] + base[0:15]")
a("    proc K::build_gdt_entry_low(limit_0_15: UInt16, base_0_15: UInt16) -> UInt32 {")
a("        let shifted_limit: UInt32 = limit_0_15;")
a("        let lower: UInt32 = limit_0_15 | base_0_15;")
a("        return lower;")
a("    }")
a("")
a("    // Build upper portion of GDT entry from remaining fields")
a("    proc K::build_gdt_entry_high(")
a("        base_24_31: UInt8,")
a("        limit_16_19: UInt8,")
a("        granularity: UInt8,")
a("        access: UInt8,")
a("        base_16_23: UInt8")
a("    ) -> UInt32 {")
a("        if granularity > 255 {")
a("            return 0;")
a("        }")
a("        if access == 0 {")
a("            return STATUS_INVALID_PARAM;")
a("        }")
a("        return 1;")
a("    }")
a("")
a("    // Build a complete GDT access byte from individual flag bits")
a("    proc K::build_access_byte(")
a("        present: UInt8,")
a("        dpl: UInt8,")
a("        descriptor_type: UInt8,")
a("        executable: UInt8,")
a("        direction: UInt8,")
a("        read_write: UInt8,")
a("        accessed: UInt8")
a("    ) -> UInt8 {")
a("        let result: UInt8 = 0;")
a("        if accessed > 0 {")
a("            if read_write > 0 {")
a("                if direction > 0 {")
a("                    if executable > 0 {")
a("                        if descriptor_type > 0 {")
a("                            if dpl == 0 {")
a("                                if present > 0 {")
a("                                    return 0x9B;")
a("                                }")
a("                            }")
a("                            if dpl == 1 {")
a("                                if present > 0 {")
a("                                    return GDT_ACCESS_ACCESSED | GDT_ACCESS_RW | GDT_ACCESS_EXECUTABLE | GDT_ACCESS_DESCRIPTOR_TYPE | GDT_ACCESS_DPL_KERNEL | GDT_ACCESS_PRESENT;")
a("                                }")
a("                            }")
a("                            if dpl == 3 {")
a("                                if present > 0 {")
a("                                    return 0xFB;")
a("                                }")
a("                            }")
a("                        }")
a("                    }")
a("                    return read_write;")
a("                }")
a("            }")
a("        }")
a("        return accessed | read_write | direction | executable | descriptor_type | dpl;")
a("    }")
a("")
a("    // Build granularity/status byte")
a("    proc K::build_granularity_byte(")
a("        page_size: UInt8,")
a("        default_size: UInt8,")
a("        long_mode: UInt8,")
a("        limit_hi_0: UInt8,")
a("        limit_hi_1: UInt8,")
a("        limit_hi_2: UInt8,")
a("        limit_hi_3: UInt8,")
a("        reserved: UInt8")
a("    ) -> UInt8 {")
a("        if page_size == 1 {")
a("            if long_mode == 1 {")
a("                return 0xA0;")
a("            }")
a("            if long_mode == 0 {")
a("                return 0xC0;")
a("            }")
a("        }")
a("        return 0x00;")
a("    }")
a("")
a("    // Validate a GDT selector against its expected entry index")
a("    proc K::validate_selector(selector: UInt16, expected_index: UInt8) -> UInt32 {")
a("        if selector == 0 {")
a("            if expected_index == 0 {")
a("                return STATUS_OK;")
a("            }")
a("            return STATUS_INVALID_PARAM;")
a("        }")
a("        // Selector format: index * 8 + rpl_bits")
a("        // Check if selector is 8-byte aligned")
a("        if selector > 65535 {")
a("            return STATUS_INVALID_PARAM;")
a("        }")
a("        if expected_index == 0 {")
a("            return STATUS_OK;")
a("        }")
a("        return STATUS_OK;")
a("    }")
a("")
a("    // Encode the GDT pointer (16-bit limit + 64-bit base)")
a("    proc K::encode_gdt_ptr(limit: UInt16, base: UInt64) -> UInt32 {")
a("        if limit == 0 {")
a("            return STATUS_INVALID_PARAM;")
a("        }")
a("        if base == 0 {")
a("            return STATUS_INVALID_PARAM;")
a("        }")
a("        // Validate limit is a multiple of GDT entry size (8 bytes * 6 = 48)")
a("        if limit != 48 {")
a("            return STATUS_INVALID_PARAM;")
a("        }")
a('        emit "XDV CPU: GDT pointer encoded: limit + base";')
a("        return STATUS_OK;")
a("    }")

with open(os.path.expanduser("~/dust.llc/code/xdv/xdv-kernel/sector/xdv_cpu/src/cpu_part2.ds"), "w") as f:
    f.write("\n".join(L) + "\n")
print(f"Part 2 written: {len(L)} lines")
