#!/usr/bin/env python3
"""Generate cpu.ds - Part 1 (constants and first procedures)"""
import os

PATH = "/home/marlon/dust.llc/code/xdv/xdv-kernel/sector/xdv_cpu/src/cpu.ds"

lines = []
A = lines.append

A('// File: cpu.ds - This file is part of XDV')
A('// Copyright (c) 2026 Dust LLC, and Contributors')
A('// Description:')
A('//   XDV Kernel - CPU Management and Control')
A('')
A('forge XdvCpu {')
A('')
A('    // =========================================================================')
A('    // Status codes')
A('    // =========================================================================')
A('')
A('    const STATUS_OK: UInt32 = 0;')
A('    const STATUS_INIT_ERROR: UInt32 = 1;')
A('    const STATUS_INVALID_PARAM: UInt32 = 2;')
A('    const STATUS_UNSUPPORTED: UInt32 = 3;')
A('    const STATUS_OVERFLOW: UInt32 = 4;')
A('    const STATUS_DOUBLE_FAULT: UInt32 = 5;')
A('    const STATUS_TRIPLE_FAULT: UInt32 = 6;')
A('    const STATUS_MSR_INVALID: UInt32 = 7;')
A('    const STATUS_CPUID_ERROR: UInt32 = 8;')
A('')
A('    // =========================================================================')
A('    // Exception vector constants (x86-64 CPU exceptions, vectors 0-31)')
A('    // =========================================================================')
A('')
A('    const EXCEPTION_DE: UInt8 = 0;')
A('    const EXCEPTION_DB: UInt8 = 1;')
A('    const EXCEPTION_NMI: UInt8 = 2;')
A('    const EXCEPTION_BP: UInt8 = 3;')
A('    const EXCEPTION_OF: UInt8 = 4;')
A('    const EXCEPTION_BR: UInt8 = 5;')
A('    const EXCEPTION_UD: UInt8 = 6;')
A('    const EXCEPTION_NM: UInt8 = 7;')
A('    const EXCEPTION_DF: UInt8 = 8;')
A('    const EXCEPTION_RS9: UInt8 = 9;')
A('    const EXCEPTION_TS: UInt8 = 10;')
A('    const EXCEPTION_NP: UInt8 = 11;')
A('    const EXCEPTION_SS: UInt8 = 12;')
A('    const EXCEPTION_GP: UInt8 = 13;')
A('    const EXCEPTION_PF: UInt8 = 14;')
A('    const EXCEPTION_RS15: UInt8 = 15;')
A('    const EXCEPTION_MF: UInt8 = 16;')
A('    const EXCEPTION_AC: UInt8 = 17;')
A('    const EXCEPTION_MC: UInt8 = 18;')
A('    const EXCEPTION_XF: UInt8 = 19;')
A('')
A('    // =========================================================================')
A('    // IRQ mapping (vectors 32-47 for IRQ 0-15)')
A('    // =========================================================================')
A('')
A('    const IRQ_BASE: UInt8 = 32;')
A('    const IRQ_PIT: UInt8 = 32;')
A('    const IRQ_KBD: UInt8 = 33;')
A('    const IRQ_SLAVE: UInt8 = 34;')
A('    const IRQ_COM2: UInt8 = 35;')
A('    const IRQ_COM1: UInt8 = 36;')
A('    const IRQ_LPT2: UInt8 = 37;')
A('    const IRQ_FLOPPY: UInt8 = 38;')
A('    const IRQ_LPT1: UInt8 = 39;')
A('    const IRQ_RTC: UInt8 = 40;')
A('    const IRQ_IRQ9: UInt8 = 41;')
A('    const IRQ_IRQ10: UInt8 = 42;')
A('    const IRQ_IRQ11: UInt8 = 43;')
A('    const IRQ_PS2: UInt8 = 44;')
A('    const IRQ_FPU: UInt8 = 45;')
A('    const IRQ_PRIMARY_ATA: UInt8 = 46;')
A('    const IRQ_SECONDARY_ATA: UInt8 = 47;')
A('')
A('    // =========================================================================')
A('    // GDT segment selectors')
A('    // =========================================================================')
A('')
A('    const GDT_NULL_SELECTOR: UInt16 = 0x0000;')
A('    const GDT_KERNEL_CODE_SELECTOR: UInt16 = 0x0008;')
A('    const GDT_KERNEL_DATA_SELECTOR: UInt16 = 0x0010;')
A('    const GDT_USER_CODE_SELECTOR: UInt16 = 0x001B;')
A('    const GDT_USER_DATA_SELECTOR: UInt16 = 0x0023;')
A('    const GDT_TSS_SELECTOR: UInt16 = 0x0028;')
A('    const GDT_NUM_ENTRIES: UInt8 = 6;')
A('')
A('    // =========================================================================')
A('    // IDT configuration')
A('    // =========================================================================')
A('')
A('    const IDT_NUM_ENTRIES: UInt8 = 256;')
A('    const IDT_ENTRY_SIZE: UInt8 = 16;')
A('')
A('    // =========================================================================')
A('    // GDT access byte constants')
A('    // (bit 0=accessed, bit 1=rw, bit 2=dc, bit 3=exec, bit 4=descriptor type,')
A('    //  bits 5-6=DPL, bit 7=present)')
A('    // =========================================================================')
A('')
A('    const GDT_ACCESS_ACCESSED: UInt8 = 0x01;')
A('    const GDT_ACCESS_RW: UInt8 = 0x02;')
A('    const GDT_ACCESS_DC: UInt8 = 0x04;')
A('    const GDT_ACCESS_EXECUTABLE: UInt8 = 0x08;')
A('    const GDT_ACCESS_DESCRIPTOR_TYPE: UInt8 = 0x10;')
A('    const GDT_ACCESS_DPL_KERNEL: UInt8 = 0x00;')
A('    const GDT_ACCESS_DPL_USER: UInt8 = 0x60;')
A('    const GDT_ACCESS_PRESENT: UInt8 = 0x80;')
A('')
A('    const GDT_ACCESS_KERNEL_CODE: UInt8 = 0x9B;')
A('    const GDT_ACCESS_KERNEL_DATA: UInt8 = 0x93;')
A('    const GDT_ACCESS_USER_CODE: UInt8 = 0xFB;')
A('    const GDT_ACCESS_USER_DATA: UInt8 = 0xF3;')
A('    const GDT_ACCESS_TSS: UInt8 = 0x89;')
A('')
A('    // =========================================================================')
A('    // GDT granularity byte constants')
A('    // (bit 7=4KB page, bit 6=32-bit, bit 5=64-bit code, bits 4-0=limit upper)')
A('    // =========================================================================')
A('')
A('    const GDT_GRANULARITY_4KB: UInt8 = 0x80;')
A('    const GDT_GRANULARITY_32: UInt8 = 0x40;')
A('    const GDT_GRANULARITY_64BIT: UInt8 = 0x20;')
A('')
A('    const GDT_GRAN_KERNEL_CODE: UInt8 = 0xA0;')
A('    const GDT_GRAN_KERNEL_DATA: UInt8 = 0xC0;')
A('    const GDT_GRAN_USER_CODE: UInt8 = 0xA0;')
A('    const GDT_GRAN_USER_DATA: UInt8 = 0xC0;')
A('    const GDT_GRAN_TSS: UInt8 = 0x00;')
A('')
A('    // =========================================================================')
A('    // GDT physical addresses')
A('    // =========================================================================')
A('')
A('    const GDT_BASE_ADDRESS: UInt64 = 1073741824;')
A('    const GDT_LIMIT: UInt16 = 48;')
A('    const GDT_POINTER_ADDRESS: UInt64 = 1073741888;')
A('')
A('    // =========================================================================')
A('    // IDT physical configuration')
A('    // =========================================================================')
A('')
A('    const IDT_BASE_ADDRESS: UInt64 = 1073807360;')
A('    const IDT_LIMIT: UInt16 = 4095;')
A('    const IDT_POINTER_ADDRESS: UInt64 = 1073811456;')
A('')
A('    // =========================================================================')
A('    // TSS configuration')
A('    // =========================================================================')
A('')
A('    const TSS_BASE_ADDRESS: UInt64 = 1073876992;')
A('    const TSS_SIZE: UInt32 = 104;')
A('')
A('    // =========================================================================')
A('    // Page fault error code bits')
A('    // =========================================================================')
A('')
A('    const PF_ERR_PRESENT: UInt8 = 0x01;')
A('    const PF_ERR_WRITE: UInt8 = 0x02;')
A('    const PF_ERR_USER: UInt8 = 0x04;')
A('    const PF_ERR_RESERVED: UInt8 = 0x08;')
A('    const PF_ERR_INSTRUCTION: UInt8 = 0x10;')
A('')
A('    // =========================================================================')
A('    // CR0 flag bits (Control Register 0)')
A('    // =========================================================================')
A('')
A('    const CR0_PE: UInt64 = 1;')
A('    const CR0_MP: UInt64 = 2;')
A('    const CR0_EM: UInt64 = 4;')
A('    const CR0_TS: UInt64 = 8;')
A('    const CR0_ET: UInt64 = 16;')
A('    const CR0_NE: UInt64 = 32;')
A('    const CR0_WP: UInt64 = 65536;')
A('    const CR0_AM: UInt64 = 262144;')
A('    const CR0_PG: UInt64 = 2147483648;')
A('')
A('    // =========================================================================')
A('    // CR4 flag bits (Control Register 4)')
A('    // =========================================================================')
A('')
A('    const CR4_VME: UInt64 = 1;')
A('    const CR4_PVI: UInt64 = 2;')
A('    const CR4_TSD: UInt64 = 4;')
A('    const CR4_DE: UInt64 = 8;')
A('    const CR4_PSE: UInt64 = 16;')
A('    const CR4_PAE: UInt64 = 32;')
A('    const CR4_MCE: UInt64 = 64;')
A('    const CR4_FXSR: UInt64 = 512;')
A('    const CR4_XSAVE: UInt64 = 262144;')
A('    const CR4_SMEP: UInt64 = 1048576;')
A('    const CR4_SMAP: UInt64 = 524288;')
A('')
A('    // =========================================================================')
A('    // MSRs (Model-Specific Registers)')
A('    // =========================================================================')
A('')
A('    const MSR_IA32_EFER: UInt32 = 3221225600;')
A('    const MSR_IA32_LSTAR: UInt32 = 3221225602;')
A('    const MSR_IA32_STAR: UInt32 = 3221225601;')
A('    const MSR_IA32_SFMASK: UInt32 = 3221225604;')
A('    const MSR_IA32_APIC_BASE: UInt32 = 29;')
A('    const MSR_IA32_TSC: UInt32 = 16;')
A('')
A('    // =========================================================================')
A('    // EFER (Extended Feature Enable Register) bits')
A('    // =========================================================================')
A('')
A('    const EFER_SCE: UInt64 = 1;')
A('    const EFER_LME: UInt64 = 256;')
A('    const EFER_LMA: UInt64 = 1024;')
A('    const EFER_NXE: UInt64 = 2048;')
A('')
A('    // =========================================================================')
A('    // CPUID constants')
A('    // =========================================================================')
A('')
A('    const CPUID_LEAF_VENDOR_MAX: UInt32 = 0x00000000;')
A('    const CPUID_LEAF_FEATURES: UInt32 = 0x00000001;')
A('    const CPUID_LEAF_EXTENDED: UInt32 = 0x80000001;')
A('    const CPUID_LEAF_BRAND_STRING_0: UInt32 = 0x80000002;')
A('    const CPUID_LEAF_BRAND_STRING_1: UInt32 = 0x80000003;')
A('    const CPUID_LEAF_BRAND_STRING_2: UInt32 = 0x80000004;')
A('')
A('    const CPUID_FEAT_BIT_PSE: UInt32 = 3;')
A('    const CPUID_FEAT_BIT_PAE: UInt32 = 6;')
A('    const CPUID_FEAT_BIT_APIC: UInt32 = 9;')
A('    const CPUID_FEAT_BIT_MCA: UInt32 = 15;')
A('    const CPUID_FEAT_BIT_PAT: UInt32 = 16;')
A('    const CPUID_FEAT_BIT_CLFLUSH: UInt32 = 19;')
A('    const CPUID_FEAT_BIT_MMX: UInt32 = 23;')
A('    const CPUID_FEAT_BIT_FXSR: UInt32 = 24;')
A('    const CPUID_FEAT_BIT_SSE: UInt32 = 25;')
A('    const CPUID_FEAT_BIT_SSE2: UInt32 = 26;')
A('')
A('    const CPUID_EXT_BIT_SYSCALL: UInt32 = 11;')
A('    const CPUID_EXT_BIT_NX: UInt32 = 20;')
A('    const CPUID_EXT_BIT_RDTSCP: UInt32 = 27;')
A('    const CPUID_EXT_BIT_LM: UInt32 = 29;')
A('')
A('    // =========================================================================')
A('    // Boot defaults')
A('    // =========================================================================')
A('')
A('    const CR0_BOOT: UInt64 = 1;')
A('    const CR2_BOOT: UInt64 = 0;')
A('    const CR4_BOOT: UInt64 = 32;')
A('    const EFER_BOOT: UInt64 = 257;')
A('    const STACK_POINTER_BOOT: UInt64 = 2147483648;')
A('    const INSTRUCTION_POINTER_BOOT: UInt64 = 1048576;')

with open(PATH, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print(f"Part 1 written: {len(lines)} lines")
