import os

L = []
a = L.append

a("// File: cpu.ds - This file is part of XDV")
a("// Copyright (c) 2026 Dust LLC, and Contributors")
a("// Description:")
a("//   XDV Kernel - CPU Management and Control")
a("")
a("forge XdvCpu {")
a("")
a("    // =========================================================================")
a("    // Status codes")
a("    // =========================================================================")
a("")
a("    const STATUS_OK: UInt32 = 0;")
a("    const STATUS_INIT_ERROR: UInt32 = 1;")
a("    const STATUS_INVALID_PARAM: UInt32 = 2;")
a("    const STATUS_UNSUPPORTED: UInt32 = 3;")
a("    const STATUS_OVERFLOW: UInt32 = 4;")
a("    const STATUS_DOUBLE_FAULT: UInt32 = 5;")
a("    const STATUS_TRIPLE_FAULT: UInt32 = 6;")
a("    const STATUS_MSR_INVALID: UInt32 = 7;")
a("    const STATUS_CPUID_ERROR: UInt32 = 8;")
a("")
a("    // =========================================================================")
a("    // Exception vector constants (x86-64 CPU exceptions, vectors 0-31)")
a("    // =========================================================================")
a("")
a("    const EXCEPTION_DE: UInt8 = 0;")
a("    const EXCEPTION_DB: UInt8 = 1;")
a("    const EXCEPTION_NMI: UInt8 = 2;")
a("    const EXCEPTION_BP: UInt8 = 3;")
a("    const EXCEPTION_OF: UInt8 = 4;")
a("    const EXCEPTION_BR: UInt8 = 5;")
a("    const EXCEPTION_UD: UInt8 = 6;")
a("    const EXCEPTION_NM: UInt8 = 7;")
a("    const EXCEPTION_DF: UInt8 = 8;")
a("    const EXCEPTION_RS9: UInt8 = 9;")
a("    const EXCEPTION_TS: UInt8 = 10;")
a("    const EXCEPTION_NP: UInt8 = 11;")
a("    const EXCEPTION_SS: UInt8 = 12;")
a("    const EXCEPTION_GP: UInt8 = 13;")
a("    const EXCEPTION_PF: UInt8 = 14;")
a("    const EXCEPTION_RS15: UInt8 = 15;")
a("    const EXCEPTION_MF: UInt8 = 16;")
a("    const EXCEPTION_AC: UInt8 = 17;")
a("    const EXCEPTION_MC: UInt8 = 18;")
a("    const EXCEPTION_XF: UInt8 = 19;")
a("")
a("    // =========================================================================")
a("    // IRQ mapping (vectors 32-47 for IRQ 0-15)")
a("    // =========================================================================")
a("")
a("    const IRQ_BASE: UInt8 = 32;")
a("    const IRQ_PIT: UInt8 = 32;")
a("    const IRQ_KBD: UInt8 = 33;")
a("    const IRQ_SLAVE: UInt8 = 34;")
a("    const IRQ_COM2: UInt8 = 35;")
a("    const IRQ_COM1: UInt8 = 36;")
a("    const IRQ_LPT2: UInt8 = 37;")
a("    const IRQ_FLOPPY: UInt8 = 38;")
a("    const IRQ_LPT1: UInt8 = 39;")
a("    const IRQ_RTC: UInt8 = 40;")
a("    const IRQ_IRQ9: UInt8 = 41;")
a("    const IRQ_IRQ10: UInt8 = 42;")
a("    const IRQ_IRQ11: UInt8 = 43;")
a("    const IRQ_PS2: UInt8 = 44;")
a("    const IRQ_FPU: UInt8 = 45;")
a("    const IRQ_PRIMARY_ATA: UInt8 = 46;")
a("    const IRQ_SECONDARY_ATA: UInt8 = 47;")
a("")
a("    // =========================================================================")
a("    // GDT segment selectors")
a("    // =========================================================================")
a("")
a("    const GDT_NULL_SELECTOR: UInt16 = 0x0000;")
a("    const GDT_KERNEL_CODE_SELECTOR: UInt16 = 0x0008;")
a("    const GDT_KERNEL_DATA_SELECTOR: UInt16 = 0x0010;")
a("    const GDT_USER_CODE_SELECTOR: UInt16 = 0x001B;")
a("    const GDT_USER_DATA_SELECTOR: UInt16 = 0x0023;")
a("    const GDT_TSS_SELECTOR: UInt16 = 0x0028;")
a("    const GDT_NUM_ENTRIES: UInt8 = 6;")
a("")
a("    // =========================================================================")
a("    // IDT configuration")
a("    // =========================================================================")
a("")
a("    const IDT_NUM_ENTRIES: UInt8 = 256;")
a("    const IDT_ENTRY_SIZE: UInt8 = 16;")
a("")
a("    // =========================================================================")
a("    // GDT access byte constants")
a("    // (bit 0=accessed, bit 1=rw, bit 2=dc, bit 3=exec, bit 4=descriptor type,")
a("    //  bits 5-6=DPL, bit 7=present)")
a("    // =========================================================================")
a("")
a("    const GDT_ACCESS_ACCESSED: UInt8 = 0x01;")
a("    const GDT_ACCESS_RW: UInt8 = 0x02;")
a("    const GDT_ACCESS_DC: UInt8 = 0x04;")
a("    const GDT_ACCESS_EXECUTABLE: UInt8 = 0x08;")
a("    const GDT_ACCESS_DESCRIPTOR_TYPE: UInt8 = 0x10;")
a("    const GDT_ACCESS_DPL_KERNEL: UInt8 = 0x00;")
a("    const GDT_ACCESS_DPL_USER: UInt8 = 0x60;")
a("    const GDT_ACCESS_PRESENT: UInt8 = 0x80;")
a("")
a("    const GDT_ACCESS_KERNEL_CODE: UInt8 = 0x9B;")
a("    const GDT_ACCESS_KERNEL_DATA: UInt8 = 0x93;")
a("    const GDT_ACCESS_USER_CODE: UInt8 = 0xFB;")
a("    const GDT_ACCESS_USER_DATA: UInt8 = 0xF3;")
a("    const GDT_ACCESS_TSS: UInt8 = 0x89;")
a("")
a("    // =========================================================================")
a("    // GDT granularity byte constants")
a("    // (bit 7=4KB page, bit 6=32-bit, bit 5=64-bit code, bits 4-0=limit upper)")
a("    // =========================================================================")
a("")
a("    const GDT_GRANULARITY_4KB: UInt8 = 0x80;")
a("    const GDT_GRANULARITY_32: UInt8 = 0x40;")
a("    const GDT_GRANULARITY_64BIT: UInt8 = 0x20;")
a("")
a("    const GDT_GRAN_KERNEL_CODE: UInt8 = 0xA0;")
a("    const GDT_GRAN_KERNEL_DATA: UInt8 = 0xC0;")
a("    const GDT_GRAN_USER_CODE: UInt8 = 0xA0;")
a("    const GDT_GRAN_USER_DATA: UInt8 = 0xC0;")
a("    const GDT_GRAN_TSS: UInt8 = 0x00;")
a("")
a("    // =========================================================================")
a("    // GDT physical addresses")
a("    // =========================================================================")
a("")
a("    const GDT_BASE_ADDRESS: UInt64 = 1073741824;")
a("    const GDT_LIMIT: UInt16 = 48;")
a("    const GDT_POINTER_ADDRESS: UInt64 = 1073741888;")
a("")
a("    // =========================================================================")
a("    // IDT physical configuration")
a("    // =========================================================================")
a("")
a("    const IDT_BASE_ADDRESS: UInt64 = 1073807360;")
a("    const IDT_LIMIT: UInt16 = 4095;")
a("    const IDT_POINTER_ADDRESS: UInt64 = 1073811456;")
a("")
a("    // =========================================================================")
a("    // TSS configuration")
a("    // =========================================================================")
a("")
a("    const TSS_BASE_ADDRESS: UInt64 = 1073876992;")
a("    const TSS_SIZE: UInt32 = 104;")
a("")
a("    // =========================================================================")
a("    // Page fault error code bits")
a("    // =========================================================================")
a("")
a("    const PF_ERR_PRESENT: UInt8 = 0x01;")
a("    const PF_ERR_WRITE: UInt8 = 0x02;")
a("    const PF_ERR_USER: UInt8 = 0x04;")
a("    const PF_ERR_RESERVED: UInt8 = 0x08;")
a("    const PF_ERR_INSTRUCTION: UInt8 = 0x10;")
a("")
a("    // =========================================================================")
a("    // CR0 flag bits (Control Register 0)")
a("    // =========================================================================")
a("")
a("    const CR0_PE: UInt64 = 1;")
a("    const CR0_MP: UInt64 = 2;")
a("    const CR0_EM: UInt64 = 4;")
a("    const CR0_TS: UInt64 = 8;")
a("    const CR0_ET: UInt64 = 16;")
a("    const CR0_NE: UInt64 = 32;")
a("    const CR0_WP: UInt64 = 65536;")
a("    const CR0_AM: UInt64 = 262144;")
a("    const CR0_PG: UInt64 = 2147483648;")
a("")
a("    // =========================================================================")
a("    // CR4 flag bits (Control Register 4)")
a("    // =========================================================================")
a("")
a("    const CR4_VME: UInt64 = 1;")
a("    const CR4_PVI: UInt64 = 2;")
a("    const CR4_TSD: UInt64 = 4;")
a("    const CR4_DE: UInt64 = 8;")
a("    const CR4_PSE: UInt64 = 16;")
a("    const CR4_PAE: UInt64 = 32;")
a("    const CR4_MCE: UInt64 = 64;")
a("    const CR4_FXSR: UInt64 = 512;")
a("    const CR4_XSAVE: UInt64 = 262144;")
a("    const CR4_SMEP: UInt64 = 1048576;")
a("    const CR4_SMAP: UInt64 = 524288;")
a("")
a("    // =========================================================================")
a("    // MSRs (Model-Specific Registers)")
a("    // =========================================================================")
a("")
a("    const MSR_IA32_EFER: UInt32 = 3221225600;")
a("    const MSR_IA32_LSTAR: UInt32 = 3221225602;")
a("    const MSR_IA32_STAR: UInt32 = 3221225601;")
a("    const MSR_IA32_SFMASK: UInt32 = 3221225604;")
a("    const MSR_IA32_APIC_BASE: UInt32 = 29;")
a("    const MSR_IA32_FS_BASE: UInt32 = 3221225600;")
a("    const MSR_IA32_GS_BASE: UInt32 = 3221225601;")
a("    const MSR_IA32_KERNEL_GS_BASE: UInt32 = 3221225602;")
a("    const MSR_IA32_TSC: UInt32 = 16;")
a("")
a("    // =========================================================================")
a("    // EFER (Extended Feature Enable Register) bits")
a("    // =========================================================================")
a("")
a("    const EFER_SCE: UInt64 = 1;")
a("    const EFER_LME: UInt64 = 256;")
a("    const EFER_LMA: UInt64 = 1024;")
a("    const EFER_NXE: UInt64 = 2048;")
a("")
a("    // =========================================================================")
a("    // CPUID constants")
a("    // =========================================================================")
a("")
a("    const CPUID_LEAF_VENDOR_MAX: UInt32 = 0x00000000;")
a("    const CPUID_LEAF_FEATURES: UInt32 = 0x00000001;")
a("    const CPUID_LEAF_EXTENDED: UInt32 = 0x80000001;")
a("    const CPUID_LEAF_BRAND_STRING_0: UInt32 = 0x80000002;")
a("    const CPUID_LEAF_BRAND_STRING_1: UInt32 = 0x80000003;")
a("    const CPUID_LEAF_BRAND_STRING_2: UInt32 = 0x80000004;")
a("")
a("    const CPUID_FEAT_BIT_PSE: UInt32 = 3;")
a("    const CPUID_FEAT_BIT_PAE: UInt32 = 6;")
a("    const CPUID_FEAT_BIT_APIC: UInt32 = 9;")
a("    const CPUID_FEAT_BIT_MCA: UInt32 = 15;")
a("    const CPUID_FEAT_BIT_PAT: UInt32 = 16;")
a("    const CPUID_FEAT_BIT_CLFLUSH: UInt32 = 19;")
a("    const CPUID_FEAT_BIT_MMX: UInt32 = 23;")
a("    const CPUID_FEAT_BIT_FXSR: UInt32 = 24;")
a("    const CPUID_FEAT_BIT_SSE: UInt32 = 25;")
a("    const CPUID_FEAT_BIT_SSE2: UInt32 = 26;")
a("")
a("    const CPUID_EXT_BIT_SYSCALL: UInt32 = 11;")
a("    const CPUID_EXT_BIT_NX: UInt32 = 20;")
a("    const CPUID_EXT_BIT_RDTSCP: UInt32 = 27;")
a("    const CPUID_EXT_BIT_LM: UInt32 = 29;")
a("")
a("    // =========================================================================")
a("    // Boot defaults")
a("    // =========================================================================")
a("")
a("    const CR0_BOOT: UInt64 = 1;")
a("    const CR2_BOOT: UInt64 = 0;")
a("    const CR4_BOOT: UInt64 = 32;")
a("    const EFER_BOOT: UInt64 = 257;")
a("    const STACK_POINTER_BOOT: UInt64 = 2147483648;")
a("    const INSTRUCTION_POINTER_BOOT: UInt64 = 1048576;")

with open(os.path.expanduser("~/dust.llc/code/xdv/xdv-kernel/sector/xdv_cpu/src/cpu_part1.ds"), "w") as f:
    f.write("\n".join(L) + "\n")
print(f"Part 1 written: {len(L)} lines")
