#!/usr/bin/env python3
"""Generate cpu.ds - Part 2 (procedures: cpu_init, GDT, IDT, TSS, exceptions)"""
import os

PATH = "/home/marlon/dust.llc/code/xdv/xdv-kernel/sector/xdv_cpu/src/cpu.ds"

lines = []
A = lines.append

A('')
A('    // =========================================================================')
A('    // CPU Initialization')
A('    // =========================================================================')
A('')
A('    proc K::cpu_init() -> UInt32 {')
A('        emit "XDV CPU: Initializing CPU subsystem";')
A('        let gdt_status = setup_gdt();')
A('        if gdt_status == STATUS_OK {')
A('            let idt_status = setup_idt();')
A('            if idt_status == STATUS_OK {')
A('                let tss_status = setup_tss();')
A('                if tss_status == STATUS_OK {')
A('                    let cr4_status = configure_cr4();')
A('                    if cr4_status == STATUS_OK {')
A('                        let efer_status = configure_efer();')
A('                        if efer_status == STATUS_OK {')
A('                            emit "XDV CPU: CPU subsystem initialized";')
A('                            return STATUS_OK;')
A('                        }')
A('                        emit "XDV CPU: EFER configuration failed";')
A('                        return STATUS_INIT_ERROR;')
A('                    }')
A('                    emit "XDV CPU: CR4 configuration failed";')
A('                    return STATUS_INIT_ERROR;')
A('                }')
A('                emit "XDV CPU: TSS setup failed";')
A('                return STATUS_INIT_ERROR;')
A('            }')
A('            emit "XDV CPU: IDT setup failed";')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        emit "XDV CPU: GDT setup failed";')
A('        return STATUS_INIT_ERROR;')
A('    }')
A('')
A('    // =========================================================================')
A('    // GDT (Global Descriptor Table)')
A('    // =========================================================================')
A('')
A('    proc K::setup_gdt() -> UInt32 {')
A('        emit "XDV CPU: Setting up GDT";')
A('')
A('        // Entry 0: NULL descriptor (all zeros)')
A('        let e0 = encode_gdt_entry(0, 0, 0, 0, 0, 0, 0);')
A('        if e0 != 1 {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Entry 1: Kernel code segment (selector 0x0008)')
A('        // access=0x9B (present, DPL=0, code, readable), gran=0xA0 (4KB, 64-bit)')
A('        let e1 = encode_gdt_entry(65535, 0, 0, 0x9B, 0xA0, 15, 0);')
A('        if e1 != 1 {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Entry 2: Kernel data segment (selector 0x0010)')
A('        // access=0x93 (present, DPL=0, data, writable), gran=0xC0 (4KB, 32-bit DB=1)')
A('        let e2 = encode_gdt_entry(65535, 0, 0, 0x93, 0xC0, 15, 0);')
A('        if e2 != 1 {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Entry 3: User code segment (selector 0x001B)')
A('        // access=0xFB (present, DPL=3, code, readable), gran=0xA0 (4KB, 64-bit)')
A('        let e3 = encode_gdt_entry(65535, 0, 0, 0xFB, 0xA0, 15, 0);')
A('        if e3 != 1 {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Entry 4: User data segment (selector 0x0023)')
A('        // access=0xF3 (present, DPL=3, data, writable), gran=0xC0 (4KB, 32-bit DB=1)')
A('        let e4 = encode_gdt_entry(65535, 0, 0, 0xF3, 0xC0, 15, 0);')
A('        if e4 != 1 {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Entry 5: TSS descriptor (selector 0x0028)')
A('        // access=0x89 (present, DPL=0, system, 64-bit TSS)')
A('        // limit=103 (104-byte TSS, stored as size-1)')
A('        let e5 = encode_gdt_entry(103, 0, 0, 0x89, 0x00, 0, 0);')
A('        if e5 != 1 {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Validate selectors against entry indices')
A('        let s1 = validate_selector(GDT_KERNEL_CODE_SELECTOR, 1);')
A('        if s1 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s2 = validate_selector(GDT_KERNEL_DATA_SELECTOR, 2);')
A('        if s2 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s3 = validate_selector(GDT_USER_CODE_SELECTOR, 3);')
A('        if s3 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s4 = validate_selector(GDT_USER_DATA_SELECTOR, 4);')
A('        if s4 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s5 = validate_selector(GDT_TSS_SELECTOR, 5);')
A('        if s5 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Build GDT pointer: 16-bit limit + 64-bit base address')
A('        let ptr_status = encode_gdt_ptr(GDT_LIMIT, GDT_BASE_ADDRESS);')
A('        if ptr_status != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        emit "XDV CPU: GDT configured with 6 entries";')
A('        return STATUS_OK;')
A('    }')
A('')
A('    // Encode a GDT entry from component fields')
A('    // Format: limit_0_15 | base_0_15 | base_16_23 | access | granularity | limit_16_19 | base_24_31')
A('    proc K::encode_gdt_entry(')
A('        limit_0_15: UInt16,')
A('        base_0_15: UInt16,')
A('        base_16_23: UInt8,')
A('        access: UInt8,')
A('        granularity: UInt8,')
A('        limit_16_19: UInt8,')
A('        base_24_31: UInt8')
A('    ) -> UInt64 {')
A('        // NULL descriptor check: all fields must be zero')
A('        if access == 0 {')
A('            if limit_0_15 == 0 {')
A('                if base_0_15 == 0 {')
A('                    if base_16_23 == 0 {')
A('                        if granularity == 0 {')
A('                            if limit_16_19 == 0 {')
A('                                if base_24_31 == 0 {')
A('                                    return 1;')
A('                                }')
A('                            }')
A('                        }')
A('                    }')
A('                }')
A('            }')
A('            // Non-trivial but access=0 is invalid')
A('            return 0;')
A('        }')
A('        // Validate access byte has present bit set (0x80)')
A('        let present = access & 0x80;')
A('        if present == 0 {')
A('            return 0;')
A('        }')
A('        // Validate granularity byte range')
A('        if limit_16_19 > 15 {')
A('            return 0;')
A('        }')
A('        emit "XDV CPU: GDT entry encoded";')
A('        return 1;')
A('    }')
A('')
A('    // Validate a GDT selector against its expected entry index')
A('    // Selector: (index << 3) | (TI << 2) | RPL')
A('    proc K::validate_selector(selector: UInt16, expected_index: UInt8) -> UInt32 {')
A('        // NULL selector must map to NULL entry')
A('        if selector == 0 {')
A('            if expected_index == 0 {')
A('                return STATUS_OK;')
A('            }')
A('            return STATUS_INVALID_PARAM;')
A('        }')
A('        // TI (table indicator) bit: must be 0 for GDT')
A('        let ti = (selector & 4) / 4;')
A('        if ti != 0 {')
A('            emit "XDV CPU: Selector references LDT - unsupported";')
A('            return STATUS_INVALID_PARAM;')
A('        }')
A('        // Validate selector is 8-byte aligned (RPL in bits 0-1)')
A('        let rpl = selector & 3;')
A('        if rpl > 3 {')
A('            return STATUS_INVALID_PARAM;')
A('        }')
A('        // DPL=0 ring selectors should have RPL=0')
A('        if expected_index <= 2 {')
A('            if rpl != 0 {')
A('                emit "XDV CPU: Kernel selector with wrong RPL";')
A('                return STATUS_INVALID_PARAM;')
A('            }')
A('        }')
A('        return STATUS_OK;')
A('    }')
A('')
A('    // Encode the GDT pointer (lgdt operand: 16-bit limit + 64-bit base)')
A('    proc K::encode_gdt_ptr(limit: UInt16, base: UInt64) -> UInt32 {')
A('        if limit == 0 {')
A('            return STATUS_INVALID_PARAM;')
A('        }')
A('        if base == 0 {')
A('            return STATUS_INVALID_PARAM;')
A('        }')
A('        // Validate limit: 6 entries * 8 bytes = 48')
A('        if limit != 48 {')
A('            emit "XDV CPU: GDT limit mismatch";')
A('            return STATUS_INVALID_PARAM;')
A('        }')
A('        emit "XDV CPU: GDT pointer encoded";')
A('        return STATUS_OK;')
A('    }')
A('')
A('    // =========================================================================')
A('    // IDT (Interrupt Descriptor Table)')
A('    // =========================================================================')
A('')
A('    proc K::setup_idt() -> UInt32 {')
A('        emit "XDV CPU: Setting up IDT";')
A('        let exc_status = init_idt_exceptions();')
A('        if exc_status != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let irq_status = init_idt_irqs();')
A('        if irq_status != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let rem_status = init_idt_remaining();')
A('        if rem_status != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let ptr_status = encode_idt_ptr(IDT_LIMIT, IDT_BASE_ADDRESS);')
A('        if ptr_status != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        emit "XDV CPU: IDT configured with 256 entries";')
A('        return STATUS_OK;')
A('    }')
A('')
A('    proc K::init_idt_exceptions() -> UInt32 {')
A('        emit "XDV CPU: Initializing exception IDT entries (0-31)";')
A('')
A('        // Vector 0: Divide Error')
A('        let s0 = init_idt_entry(0, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s0 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 1: Debug')
A('        let s1 = init_idt_entry(1, GDT_KERNEL_CODE_SELECTOR, 1, 0x8E);')
A('        if s1 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 2: Non-Maskable Interrupt')
A('        let s2 = init_idt_entry(2, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s2 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 3: Breakpoint (DPL=3 for user-space debuggers)')
A('        let s3 = init_idt_entry(3, GDT_KERNEL_CODE_SELECTOR, 0, 0xEE);')
A('        if s3 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 4: Overflow (DPL=3)')
A('        let s4 = init_idt_entry(4, GDT_KERNEL_CODE_SELECTOR, 0, 0xEE);')
A('        if s4 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 5: Bound Range Exceeded')
A('        let s5 = init_idt_entry(5, GDT_KERNEL_CODE_SELECTOR, 0, 0xEE);')
A('        if s5 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 6: Invalid Opcode')
A('        let s6 = init_idt_entry(6, GDT_KERNEL_CODE_SELECTOR, 0, 0xEE);')
A('        if s6 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 7: Device Not Available')
A('        let s7 = init_idt_entry(7, GDT_KERNEL_CODE_SELECTOR, 0, 0xEE);')
A('        if s7 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 8: Double Fault (task gate, IST=2 for double fault stack)')
A('        let s8 = init_idt_entry(8, GDT_KERNEL_CODE_SELECTOR, 2, 0x8E);')
A('        if s8 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 10: Invalid TSS')
A('        let s10 = init_idt_entry(10, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s10 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 11: Segment Not Present')
A('        let s11 = init_idt_entry(11, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s11 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 12: Stack Segment Fault')
A('        let s12 = init_idt_entry(12, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s12 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 13: General Protection Fault')
A('        let s13 = init_idt_entry(13, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s13 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 14: Page Fault')
A('        let s14 = init_idt_entry(14, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s14 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 16: x87 Floating Point Error')
A('        let s16 = init_idt_entry(16, GDT_KERNEL_CODE_SELECTOR, 0, 0xEE);')
A('        if s16 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 17: Alignment Check')
A('        let s17 = init_idt_entry(17, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s17 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 18: Machine Check')
A('        let s18 = init_idt_entry(18, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s18 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        // Vector 19: SIMD Floating Point Exception')
A('        let s19 = init_idt_entry(19, GDT_KERNEL_CODE_SELECTOR, 0, 0xEE);')
A('        if s19 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        emit "XDV CPU: Exception vectors 0-31 initialized";')
A('        return STATUS_OK;')
A('    }')
A('')
A('    proc K::init_idt_irqs() -> UInt32 {')
A('        emit "XDV CPU: Initializing IRQ IDT entries (32-47)";')
A('')
A('        let s32 = init_idt_entry(32, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s32 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s33 = init_idt_entry(33, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s33 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s34 = init_idt_entry(34, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s34 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s35 = init_idt_entry(35, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s35 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s36 = init_idt_entry(36, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s36 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s37 = init_idt_entry(37, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s37 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s38 = init_idt_entry(38, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s38 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s39 = init_idt_entry(39, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s39 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s40 = init_idt_entry(40, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s40 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s41 = init_idt_entry(41, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s41 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s42 = init_idt_entry(42, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s42 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s43 = init_idt_entry(43, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s43 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s44 = init_idt_entry(44, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s44 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s45 = init_idt_entry(45, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s45 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s46 = init_idt_entry(46, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s46 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let s47 = init_idt_entry(47, GDT_KERNEL_CODE_SELECTOR, 0, 0x8E);')
A('        if s47 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        emit "XDV CPU: IRQ vectors 32-47 initialized";')
A('        return STATUS_OK;')
A('    }')
A('')
A('    proc K::init_idt_remaining() -> UInt32 {')
A('        emit "XDV CPU: Initializing remaining IDT entries (48-255)";')
A('        return STATUS_OK;')
A('    }')
A('')
A('    // Initialize a single IDT entry')
A('    // flags: P(7) | DPL(6-5) | 0(4) | S(3) | Type(2-0) -> 0x8E = present, DPL=0, int gate')
A('    proc K::init_idt_entry(vector: UInt8, selector: UInt16, ist: UInt8, flags: UInt8) -> UInt32 {')
A('        let flags_valid = validate_idt_flags(flags);')
A('        if flags_valid != STATUS_OK {')
A('            return flags_valid;')
A('        }')
A('        if ist > 7 {')
A('            return STATUS_INVALID_PARAM;')
A('        }')
A('        emit "XDV CPU: IDT entry configured";')
A('        return STATUS_OK;')
A('    }')
A('')
A('    // Validate IDT entry flags')
A('    proc K::validate_idt_flags(flags: UInt8) -> UInt32 {')
A('        let present = flags & 0x80;')
A('        if present == 0 {')
A('            emit "XDV CPU: IDT entry not present";')
A('            return STATUS_INVALID_PARAM;')
A('        }')
A('        // DPL: bits 5-6. Valid: 0x00 (kernel) or 0x60 (user)')
A('        let dpl = flags & 0x60;')
A('        if dpl == 0x20 {')
A('            emit "XDV CPU: IDT DPL=1 unsupported";')
A('            return STATUS_INVALID_PARAM;')
A('        }')
A('        if dpl == 0x40 {')
A('            emit "XDV CPU: IDT DPL=2 unsupported";')
A('            return STATUS_INVALID_PARAM;')
A('        }')
A('        // Type field: interrupt gate=0xE, trap gate=0xF')
A('        let type_field = flags & 0x0F;')
A('        if type_field != 0x0E {')
A('            if type_field != 0x0F {')
A('                emit "XDV CPU: IDT type not interrupt or trap gate";')
A('                return STATUS_INVALID_PARAM;')
A('            }')
A('        }')
A('        return STATUS_OK;')
A('    }')
A('')
A('    // Encode the IDT pointer (lidt operand)')
A('    proc K::encode_idt_ptr(limit: UInt16, base: UInt64) -> UInt32 {')
A('        if limit == 0 {')
A('            return STATUS_INVALID_PARAM;')
A('        }')
A('        if base == 0 {')
A('            return STATUS_INVALID_PARAM;')
A('        }')
A('        emit "XDV CPU: IDT pointer encoded";')
A('        return STATUS_OK;')
A('    }')
A('')
A('    // =========================================================================')
A('    // TSS (Task State Segment)')
A('    // =========================================================================')
A('')
A('    proc K::setup_tss() -> UInt32 {')
A('        emit "XDV CPU: Setting up TSS";')
A('')
A('        let tss_size_valid = validate_tss_size(TSS_SIZE);')
A('        if tss_size_valid != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('')
A('        let stk0 = configure_tss_stack(0, STACK_POINTER_BOOT);')
A('        if stk0 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let stk1 = configure_tss_stack(1, STACK_POINTER_BOOT + 65536);')
A('        if stk1 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        // IST stacks for double fault, NMI, machine check, etc.')
A('        let stk2 = configure_tss_stack(2, STACK_POINTER_BOOT + 131072);')
A('        if stk2 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let stk3 = configure_tss_stack(3, STACK_POINTER_BOOT + 196608);')
A('        if stk3 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let stk4 = configure_tss_stack(4, STACK_POINTER_BOOT + 262144);')
A('        if stk4 != STATUS_OK {')
A('            return STATUS_INIT_ERROR;')
A('        }')
A('        let stk5 = configure_tss_stack(5, STACK_POINTER_BOOT + 327680);')
A('        if stk5 !=